sglyon/PlotlyBase.jl

src/api.jl

first commit fix restyle! docstring. This was preventing the docstring from showing up in REPL's help
Other commit are some improve to the other docstring in the file, so that in the REPL the method signature is shown

fix some docstrings

---

REQUIRE
src/PlotlyBase.jl
src/convenience_api.jl
src/dataframes_api.jl
src/styles.jl

Julia v1.0 uses the [Logging](https://docs.julialang.org/en/v1/stdlib/Logging/index.html) package and a [macro for warn](https://docs.julialang.org/en/v1/stdlib/Logging/index.html).
I updated two Julia files + added `using Logging` in `PlotlyBase.jl` and `REQUIRE`.
**Not fully tested**

Updating the warn function for Julia v1.0

---

src/PlotlyBase.jl

This doesn't seem to be defined anymore

Remove `init_notebook` export

---

src/convenience_api.jl

currently `stem` fails with this simple example:
using PlotlyJS
x = [1,2,3]
y = [1,-1,1]
stem(;x=x, y=y)
this pull request fixes the issue by changing `min` and `max` to the elementwise `min.` and `max.`

change min/max to min./max. in stem

---

Project.toml
src/dataframes_api.jl

Switches from `haskey(df, colname)` to `hasproperty(df, colname)` and from `df[colname]` to `df[!, colname]`.
I guess that requires DataFrames v0.19 (or a bit earlier), but since it's an optional dependency, the check has yet to be coded in `__init__()`, which I can try to implement if needed.

Fix DataFrames v0.19 deprecations

---

Artifacts.toml
Manifest.toml
Project.toml
create_artifact_script.jl
src/PlotlyBase.jl
src/kaleido.jl

@staticfloat thanks for trying to help me over in PlotlyJS.jl
I am learning the artifacts system.
I've tried to get things started over here using plotly's new static image exporter kaleido.
With the config in this repo, when I try to do `using PlotlyBase` I get 
```
julia> using PlotlyBase
[ Info: Precompiling PlotlyBase [a03496cd-edff-5a9b-9e67-9cda94a718b5]
ERROR: LoadError: LoadError: LoadError: Cannot locate '(Julia)Artifacts.toml' file when attempting to use artifact 'kaleido' in 'PlotlyBase'
Stacktrace:
```
Any idea how to fix this?
Note I did `]dev PlotlyBase`, checked out ~/.julia/dev/PlotlyBase to the kaleido dir, and then activated the project.

ENH: integrate kaleido to save/export figures

---

src/kaleido.jl

When we add PlotlyBase.jl to Windows SYSIMG on Julia v1.6.1, we encounter following warning during REPL startup, this PR fixes this warning.
```
┌ Warning: Kaleido is not available on this system. Julia will be unable to save images of any plots.
└ @ PlotlyBase C:\Users\julia\.julia\packages\PlotlyBase\GDbp9\src\kaleido.jl:65
┌ Warning: ErrorException("Could not start Kaleido process")
└ @ PlotlyBase C:\Users\julia\.julia\packages\PlotlyBase\GDbp9\src\kaleido.jl:66
_
_       _ _(_)_     |  Documentation: https://docs.julialang.org
(_)     | (_) (_)    |
_ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
| | | | | | |/ _` |  |
| | |_| | | | (_| |  |  Version 1.6.1 (2021-04-23)
_/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |
julia>
``` …

Fixes "Kaleido is not available" warning on Windows

---

src/output.jl

Currently, the to_html function is broken if we specify configuration options such as showLink or make use of frames to display animations. This PR fixed these issues for my purposes.

Fix html export with options/animations

---

src/plot_config.jl

fixes https://github.com/sglyon/PlotlyBase.jl/issues/60 as promised. Manually tested using
```jl
using PlotlyBase, JSON
config = PlotConfig(modeBarButtons=[["toImage"]])
p = Plot(GenericTrace[], Layout(); config)
str = JSON.json(p)
contains(str, "\"modeBarButtons\":[[\"toImage\"]]")
```
---
When comparing `src/plot_config.js` with the plotly.js version:
https://github.com/plotly/plotly.js/blob/51eded41ac7433a9193fe0c21439dbc5f92b6dd6/src/plot_api/plot_config.js
I've noticed a few more missing keys e.g. [`showTips`](https://github.com/plotly/plotly.js/blob/51eded41ac7433a9193fe0c21439dbc5f92b6dd6/src/plot_api/plot_config.js#L200-L207) and [`topojsonURL`](https://github.com/plotly/plotly.js/blob/51eded41ac7433a9193fe0c21439dbc5f92b6dd6/src/plot_api/plot_config.js#L356-L368). Moreover, some …

Add `modeBarButtons` to PlotConfig

---

src/json3.jl

This allows serialisable objects containing plots to be serialized, e.g. `Dict(:plot => plot(...))`
I'm afraid I missed some reason why it was implemented the way it was, but I thought I'd find out by creating a PR 😁

A little less backdoor-y support for JSON3

---

src/subplots.jl

Current concatenation magic does not work for 3d plots as the specs for specifying the domains are slightly different:
https://plotly.com/javascript/reference/layout/scene/#layout-scene-domain
The `xanchor`, `yanchor` do not seem relevant for `layout.scene` and there is a single `domain` which contains both `x` and `y`.
This simple change should fix the issue (at least on the short test I did on Pluto)

Fix 3d plot concatenation

---

Project.toml

Failing ci jobs, e.g. https://github.com/JuliaPlots/Plots.jl/runs/8048912406?check_suite_focus=true.

bump `DocStringExtensions`: fix `Plots` ci

---

src/subplots.jl

This bug results in messed up SubplotRefs when a secondary y axis is used.

fix bug in axis counter

---

ext/IJuliaExt.jl

Use `IOBuffer` without relying on implementation details. Should fix https://github.com/sglyon/PlotlyBase.jl/issues/108

Fix `IJuliaExt.display_dict` for julia 1.11

---

src/output.jl

Since Juno is essentially no longer used, let's switch to the equivalent MIME required by VSCode.

Deprecate MIME for Juno, add VSCode

---

Project.toml
ext/ColorsExt.jl
src/PlotlyBase.jl
src/json.jl

Currently, *Colors.jl* is a weak dependency, and the user needs `using Colors` to enable *ColorsExt* extension, which sole purpose is to define `_json_lower(c::Colorant)`.
However, *PlotlyBase.jl* already has *ColorSchemes.jl* as a direct dependency and defines `_json_lower(::ColorScheme)` in the main module.
But the latter method needs `_json_lower(::Colorant)` to work.
So, making `Colors.jl` a direct dependency of `PlotlyBase.jl` would simplify things a bit. It would not increase the "dependencies burden" of `PlotlyBase.jl` since `Colors.jl` is already a direct dependency of `ColorSchemes.jl`.
Also, it should solve the error
```
MethodError: Cannot `convert` an object of type JSON.Writer.CompositeTypeWrapper{RGB{Float64}} to an object of type String
```
which I am getting despite `using …

Make Colors.jl a direct dependency

---

src/traces_layouts.jl

Not less and not more than the title promises.
People may not be familiar with the `pop!` method, moreover, `delete!` returns the collection, e.g. layout rather than the property. Implementation is straight forward.

add a delete! method for HasFields

---

src/api.jl

This PR fixes #98
Currently, the default settings of a Layout overwrite existing values, with this PR only the specified values are updated.
Moreover, `update!(p_::Plot, ...)` has a similar Problem when setting the default layout to Layout. Instead I propose to set it to `p.layout`.

fix overwriting of layout by relayout! and update!

---

src/api.jl

This PR fixes #113 and extends it to all API functions.
The idea is that all API functions that act on shapes, layouts and plots, e.g. `relayout!()`, restyle!()` etc. return the modified input variable. For functions not ending with '!' this was already valid, now it is true for all functions.

consistent return types

---

src/traces_layouts.jl
test/traces.jl

The values of some *plotly.js* attributes could be dictionaries (i.e. JSON).
*PlotlyBase.jl* already partially supports that for `geojson` (of `scattergeo` trace).
Recent *plotly.js* versions has added support for axes [label aliases](https://plotly.com/javascript/reference/layout/xaxis/#layout-xaxis-labelalias), which are also dictionaries.
It allows to improve the display of axes ticks, while keeping the actual plot data lean.
The problem with the current *PlotlyBase* logic is that it treats any dictionary values as nested attributes.
The PR fixes that by defining the list of attributes that could be dictionaries (`_ASSOCIATIVE_ATTRS`) and disabling nested *attr* logic for them.
It also extends the support for dict-valued attributes for symbol-valued keys (currently only `"geojson",` …

Suppport dictionary-valued attributes

---

ext/IJuliaExt.jl

The IJuliaExt in its current form fails as the JSON dependency is directly called without being loaded in the extension module. This PR mainly prepends the PlotlyBase module to the `JSON.lower` call.
Additionally, I found that at least in Google Colab (didn't try on local IJulia) the `include_plotlyjs=require` fails on the javascript side with an error hinting at `missing require`. I did remove the kwarg as the `cdn` fallback works fine, but if for some reason the require was needed for some specific purpose I can try to have a look at how and if it can be put back.
Link to the Google colab notebook used to test:
https://colab.research.google.com/drive/1Ehx_z35JqmwjvqN3ZxupyxynziqHzE2y?usp=sharing

fix IJuliaExt

---

ext/DataFramesExt.jl

The `_symbol_dict` function was not imported from PlotlyBase in the extension module and causes an error (discovered in https://github.com/JuliaPluto/PlutoPlotly.jl/issues/62#issuecomment-2783230974)
This code path is only traversed with a non-custom `labels` kwarg which is probably not covered by tests and it was not spotted.

Fix error in DataFramesExt.jl
