sglyon/PlotlyBase.jl

- src/convenience_api.jl
linspace -> LinRange
for Julia v1.0
**I have not tested this modification.**
> linspace -> LinRange

- src/PlotlyBase.jl
Adding `STYLES` to export. For allowing users to list out available plotting styles
> add STYLES to export for listing STYLES

- src/styles.jl
To fix the issue described in #15
> add margin to each style and update (gadfly_dark)

- src/traces_layouts.jl
as per https://github.com/sglyon/PlotlyJS.jl/issues/87
> allow for datetime type in x axis

- src/PlotlyBase.jl
- src/json.jl
- src/output.jl
- src/traces_layouts.jl
- test/frames.jl
The JavaScript api allows for 'animation' mode which requires the plot json to have a frames field. The Julia code that connects to this api can be extended minimally to accommodate this functionality. This is my first time contributing here, so let me know if I missed the mark stylistically or otherwise, and I hope this helps the community.
> First pass at updating API for allowing animations

- src/dataframes_api.jl
As this is my very first PR, I am not sure I did everything correctly.
And please note that there are no new test added.
THis should fix
https://github.com/sglyon/PlotlyBase.jl/issues/34#issue-744777320
> Change by to groupby to reflect API Change with DataFrames

- src/traces_layouts.jl
- test/styles.jl
- test/traces.jl
Attempt at fixing https://github.com/sglyon/PlotlyBase.jl/issues/32
Please let me know if there's a more julian way to write this up. Cheers!
> Fix margin mutate

- create_artifact_script.jl
1. Support `Linux(:aarch64)` and `Windows(:i686)` for artifact Kaleido;
2. Upgrade artifact Kaleido from 0.0.3 to 0.1.0.
**Changes will take effect after running the script `create_artifact_script.jl`**.
> Add supported platforms and upgrade Kaleido to 0.1.0

- src/kaleido.jl
This might help, have tested locally on a macos vm, but less see what ci says... 🤞🏻
> Use `--single-process` flag to try fix MacOS issues.

- src/kaleido.jl
> Fix issue #45

- src/kaleido.jl
- test/kaleido.jl
ref 
https://github.com/JuliaPlots/PlotlyJS.jl/issues/387
> Fix savefig html

- src/subplots.jl
> support different numbers of columns in subplots

- src/PlotlyBase.jl
- src/api.jl
- src/dataframes_api.jl
- src/styles.jl
- src/subplot_utils.jl
- src/traces_layouts.jl
this introduces some quality of life changes inspired by plotly.express from the Python library
The `Plot(::DataFrame)` method understands a few more keyword arguments, which are documented in the docstring for the corresponding method.
This also includes getproperty and setproperty for HasFields types, allowing syntax like `layout.xaxis_title = "new title"` in addition to the traditional `layout[:xaxis_title] = "new_title"`
> dataframes api upgrade

- src/PlotlyBase.jl
ref https://github.com/plotly/Dash.jl/issues/118
> remove config when using JSON2.write

- src/traces_layouts.jl
ref https://github.com/plotly/Dash.jl/issues/88
> transpose when needed

- .github/workflows/artifacts.yml
- .github/workflows/ci-master-workflow.yml
- .github/workflows/ci-pr-workflow.yml
- Project.toml
- src/traces_layouts.jl
- test/Project.toml
- test/api.jl
- test/dataframes.jl
- test/runtests.jl
closes https://github.com/JuliaPlots/PlotlyJS.jl/issues/409
> always set title_text instead of title

- src/api.jl
- test/api.jl
Allow Union{"all",Colon,Int,Vector{Int}}
closes #76
> extend row/col settings for add_trace!

- src/json3.jl
- test/Project.toml
- test/json.jl
> enhancing json3 for traces

- src/output.jl
see e.g. <https://www.w3schools.com/html/html_charset.asp> as a reference
> it should be "charset" instead of "chartset" in HTML head

- Project.toml
- ext/ColorsExt.jl
- ext/DataFramesExt.jl
- ext/DistributionsExt.jl
- ext/IJuliaExt.jl
- ext/JSON3Ext.jl
- src/PlotlyBase.jl
This adds support for the weakdeps feature on Julia 1.9 and later.
> migrate to weakdeps

- Project.toml
- ext/ColorsExt.jl
- ext/JSON2Ext.jl
- ext/JSON3Ext.jl
- src/json.jl
- test/Project.toml
- test/colors.jl
This is a possible follow up with some corrections to #102
> fix json for Layout and Colorant, add tests
